/**
 * Committed RFM-logistic weights from scripts/fixtures/a3-churn-orders.json.
 * Regenerated by: npx tsx scripts/gen_a3_churn_artifacts.ts
 */

import type { LogisticModel } from '@/services/ml-logistic';

export type CommittedModelArtifact = {
  name: 'next_purchase_predictor' | 'churn_scorer';
  artifactUri: string;
  version: string;
  trainingDataSnapshot: string;
  metrics: {
    precision: number;
    recall: number;
    f1: number;
    threshold: number;
    n_train: number;
    n_test: number;
    labeled_at: string;
  };
  model: LogisticModel;
};

export const NEXT_PURCHASE_ARTIFACT: CommittedModelArtifact = {
  "name": "next_purchase_predictor",
  "artifactUri": "inline://rfm-logistic-next-purchase-v1",
  "version": "0.1.0",
  "trainingDataSnapshot": "orders=92;asOf=2025-07-01;train=30;test=14",
  "metrics": {
    "precision": 1,
    "recall": 1,
    "f1": 1,
    "threshold": 0.5,
    "n_train": 30,
    "n_test": 14,
    "labeled_at": "2025-07-01T00:00:00.000Z"
  },
  "model": {
    "weights": [
      -0.078264,
      2.555476,
      0.790912,
      0.190837
    ],
    "bias": -1.754816,
    "threshold": 0.5,
    "normalizer": {
      "mean": [
        66.733333,
        0.966667,
        104.7,
        1.766667
      ],
      "std": [
        55.372938,
        0.930352,
        94.929676,
        1.636731
      ]
    }
  }
};

export const CHURN_SCORER_ARTIFACT: CommittedModelArtifact = {
  "name": "churn_scorer",
  "artifactUri": "inline://rfm-logistic-churn-v1",
  "version": "0.1.0",
  "trainingDataSnapshot": "orders=92;asOf=2025-07-01;train=30;test=14",
  "metrics": {
    "precision": 1,
    "recall": 1,
    "f1": 1,
    "threshold": 0.5,
    "n_train": 30,
    "n_test": 14,
    "labeled_at": "2025-07-01T00:00:00.000Z"
  },
  "model": {
    "weights": [
      0.173105,
      -2.475132,
      -0.671635,
      -0.263607
    ],
    "bias": 1.73581,
    "threshold": 0.5,
    "normalizer": {
      "mean": [
        69.7,
        0.933333,
        96.566667,
        1.666667
      ],
      "std": [
        55.669052,
        0.946338,
        94.45958,
        1.649916
      ]
    }
  }
};

export function getCommittedChurnArtifacts() {
  return {
    nextPurchase: NEXT_PURCHASE_ARTIFACT,
    churn: CHURN_SCORER_ARTIFACT,
  };
}
