/**
 * Train from fixture and write committed artifact constants.
 * Run: npx tsx scripts/gen_a3_churn_artifacts.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { trainBoth, type TrainedModelResult } from '../src/services/churn-models';
import type { OrderRowForRfm } from '../src/services/rfm-features';

type Fixture = { asOf: string; orders: OrderRowForRfm[] };

function serialize(result: TrainedModelResult) {
  return {
    name: result.name,
    artifactUri: result.artifactUri,
    version: result.version,
    trainingDataSnapshot: result.trainingDataSnapshot,
    metrics: {
      precision: Number(result.metrics.precision.toFixed(4)),
      recall: Number(result.metrics.recall.toFixed(4)),
      f1: Number(result.metrics.f1.toFixed(4)),
      threshold: result.metrics.threshold,
      n_train: result.metrics.n_train,
      n_test: result.metrics.n_test,
      labeled_at: result.metrics.labeled_at,
    },
    model: {
      weights: result.model.weights.map((w) => Number(w.toFixed(6))),
      bias: Number(result.model.bias.toFixed(6)),
      threshold: result.model.threshold,
      normalizer: {
        mean: result.model.normalizer.mean.map((v) => Number(v.toFixed(6))),
        std: result.model.normalizer.std.map((v) => Number(v.toFixed(6))),
      },
    },
  };
}

const fixturePath = resolve(__dirname, 'fixtures/a3-churn-orders.json');
const fixture = JSON.parse(readFileSync(fixturePath, 'utf8')) as Fixture;
const trained = trainBoth(fixture.orders, new Date(fixture.asOf));

const next = serialize(trained.nextPurchase);
const churn = serialize(trained.churn);

const out = `/**
 * Committed RFM-logistic weights from scripts/fixtures/a3-churn-orders.json.
 * Regenerated by: npx tsx scripts/gen_a3_churn_artifacts.ts
 */

import type { LogisticModel } from '@/services/ml-logistic';

export type CommittedModelArtifact = {
  name: 'next_purchase_predictor' | 'churn_scorer';
  artifactUri: string;
  version: string;
  trainingDataSnapshot: string;
  metrics: {
    precision: number;
    recall: number;
    f1: number;
    threshold: number;
    n_train: number;
    n_test: number;
    labeled_at: string;
  };
  model: LogisticModel;
};

export const NEXT_PURCHASE_ARTIFACT: CommittedModelArtifact = ${JSON.stringify(next, null, 2)};

export const CHURN_SCORER_ARTIFACT: CommittedModelArtifact = ${JSON.stringify(churn, null, 2)};

export function getCommittedChurnArtifacts() {
  return {
    nextPurchase: NEXT_PURCHASE_ARTIFACT,
    churn: CHURN_SCORER_ARTIFACT,
  };
}
`;

const dest = resolve(__dirname, '../src/services/churn-model-artifacts.ts');
writeFileSync(dest, out);
console.log('next_purchase', next.metrics);
console.log('churn_scorer', churn.metrics);
console.log('wrote', dest);
